config/routes.rb
Rails.application.routes.draw do

  resources :purchases

  resources :stores

  resources :jewels

end

app/models/jewel.rb
class Jewel < ActiveRecord::Base
  belongs_to :store
end

app/models/store.rb
class Store < ActiveRecord::Base
has_many :jewels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jewels_controller.rb
class JewelsController < ApplicationController
  before_action :set_jewel, only: [:show, :edit, :update, :destroy]

  # GET /jewels
  # GET /jewels.json
  def index
    @jewels = Jewel.all
  end

  # GET /jewels/1
  # GET /jewels/1.json
  def show
  end

  # GET /jewels/new
  def new
    @jewel = Jewel.new
  end

  # GET /jewels/1/edit
  def edit
  end

  # POST /jewels
  # POST /jewels.json
  def create
    @jewel = Jewel.new(jewel_params)

    respond_to do |format|
      if @jewel.save
        format.html { redirect_to @jewel, notice: 'Jewel was successfully created.' }
        format.json { render :show, status: :created, location: @jewel }
      else
        format.html { render :new }
        format.json { render json: @jewel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jewels/1
  # PATCH/PUT /jewels/1.json
  def update
    respond_to do |format|
      if @jewel.update(jewel_params)
        format.html { redirect_to @jewel, notice: 'Jewel was successfully updated.' }
        format.json { render :show, status: :ok, location: @jewel }
      else
        format.html { render :edit }
        format.json { render json: @jewel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jewels/1
  # DELETE /jewels/1.json
  def destroy
    @jewel.destroy
    respond_to do |format|
      format.html { redirect_to jewels_url, notice: 'Jewel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jewel
      @jewel = Jewel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jewel_params
      params.require(:jewel).permit(:name, :picture, :description, :price, :quantity, :store_id)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
	def index
		@stores = Store.all
		@jewels = Jewel.all
	end
	def addOne
		q = Jewel.find(1)
		q.quantity += 1
		q.save
	end
	def subOne
		q = Jewel.find(1)
		q.quantity -= 1
		q.save
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :contact)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jewels_helper.rb
module JewelsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
	def addOne()
		q = Jewel.find(1)
		q.quantity += 1
		q.save
	end
	def subOne()
		q = Jewel.find(1)
		q.quantity -= 1
		q.save
	end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/jewels/_form.html.erb
<%= form_for(@jewel) do |f| %>
  <% if @jewel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jewel.errors.count, "error") %> prohibited this jewel from being saved:</h2>

      <ul>
      <% @jewel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.text_field :store_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jewels/edit.html.erb
<h1>Editing jewel</h1>

<%= render 'form' %>

<%= link_to 'Show', @jewel %> |
<%= link_to 'Back', jewels_path %>

app/views/jewels/index.html.erb
<h1>Listing jewels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Description</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jewels.each do |jewel| %>
      <tr>
        <td><%= jewel.name %></td>
        <td><%= jewel.picture %></td>
        <td><%= jewel.description %></td>
        <td><%= jewel.price %></td>
        <td><%= jewel.quantity %></td>
        <td><%= jewel.store %></td>
        <td><%= link_to 'Show', jewel %></td>
        <td><%= link_to 'Edit', edit_jewel_path(jewel) %></td>
        <td><%= link_to 'Destroy', jewel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jewel', new_jewel_path %>

app/views/jewels/new.html.erb
<h1>New jewel</h1>

<%= render 'form' %>

<%= link_to 'Back', jewels_path %>

app/views/jewels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @jewel.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @jewel.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @jewel.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @jewel.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @jewel.quantity %>
</p>

<p>
  <strong>Store:</strong>
  <%= @jewel.store %>
</p>

<%= link_to 'Edit', edit_jewel_path(@jewel) %> |
<%= link_to 'Back', jewels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gemstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/purchases/index.html.erb
<script>
function add()
{
	<% addOne() %>
}

function sub()
{
	<% subOne() %>
}

</script>
<% store = @stores.find(1) %>
<div align="center">
	<h1><%= store.name %></h1>
	<p>Phone:<%= store.contact %></p>
</div>

<% @jewels.each do |jewel| %>
<hr/>
	<div align='center'>
		<img src='<%= jewel.picture %>'>
		<h3><%= jewel.name %>: <%= jewel.price %></h3>
		<%= jewel.description %>
		<br/><br/>
			QTY:<%= jewel.quantity %>
			<button id="b" onclick='add'>Buy</button>
			<button id="s" onclick='sub'>Sell</button>
	</div>
<% end %>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.contact %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @store.contact %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>